name: stime-binder
channels: [conda-forge]
dependencies:
  - python=3.11
  - jupyterlab
  - numpy>=1.26,<2.0
  - numba>=0.59
  - scipy>=1.11
  - pandas>=2.0
  - matplotlib>=3.7,<3.9
  - networkx>=3.1
  - scikit-learn>=1.3
  - joblib
  - dcor
  - ruptures
  - tigramite
  - cdt
  - pytorch=2.2.*
  - tabulate
  - pip
  - pip:
      - causal-learn
      - causaldag
      - Rbeast
